In [2]:
import tensorflow as tf
import numpy as np
from tensorflow.contrib import rnn
import pprint
pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

In [3]:
# one hot encoding
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

In [4]:
with tf.variable_scope('one_cell') as scope:
    hidden_size = 2 # output-dimension = (2)
    cell = tf.contrib.rnn.BasicRNNCell(num_units=hidden_size)
    print(cell.output_size, cell.state_size)
    
    x_data = np.array([[h]], dtype=np.float32)
    print(x_data.shape)
    pp.pprint(x_data)
    outputs, _states = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)
    
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())
    
# hidden_size에 따라 출력 값 결정.
# cell을 만들때에는 출력 사이즈만 정해줌
# 1, 1, 4에서 4는 입력되는 배열의 벡터 수? input size?

2 2
(1, 1, 4)
array([[[1., 0., 0., 0.]]], dtype=float32)
array([[[ 0.29922858, -0.04604758]]], dtype=float32)


In [4]:
with tf.variable_scope('two_sequances') as scope:
    hidden_size = 2
    cell = tf.contrib.rnn.BasicRNNCell(num_units=hidden_size)
    x_data = np.array([[h, e, l, l, o]], dtype=np.float32)
    print(x_data.shape)
    pp.pprint(x_data)
    outputs, states = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())

# 1, 5, 4에서 5는 입력되는 sequence data의 수

(1, 5, 4)
array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]], dtype=float32)
array([[[ 0.66425943, -0.47645193],
        [-0.18617648,  0.31830648],
        [ 0.4186586 ,  0.01063345],
        [ 0.4367324 ,  0.01653041],
        [-0.43244934,  0.7380415 ]]], dtype=float32)


In [5]:
with tf.variable_scope('3_batches') as scope:
    x_data = np.array([[h, e, l, l, o],
                      [e, o, l, l, l],
                      [l, l, e, e, l]], dtype=np.float32)
    pp.pprint(x_data)
    
    hidden_size = 2
    cell = rnn.BasicLSTMCell(num_units=hidden_size, state_is_tuple=True)
    outputs, _states = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())

array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]],

       [[0., 1., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.]],

       [[0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]]], dtype=float32)
array([[[ 0.05671924,  0.07902422],
        [ 0.204413  ,  0.17168547],
        [ 0.23906136,  0.04192444],
        [ 0.2810835 , -0.014395  ],
        [ 0.24635753,  0.02573108]],

       [[ 0.17525315,  0.09564022],
        [ 0.17024322,  0.08454602],
        [ 0.26830563,  0.0149759 ],
        [ 0.29666376, -0.03639611],
        [ 0.3150009 , -0.07741114]],

       [[ 0.1533634 , -0.04904544],
        [ 0.23383932, -0.08781105],
        [ 0.3366808 , -0.00892672],
        [ 0.36999276,  0.08104818],
        [ 0.32157868, -0.0068552 ]]], dtype=float32)
