In [1]:
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)
from sklearn.preprocessing import MinMaxScaler

In [2]:
import_data = np.genfromtxt('./daehwan.csv', delimiter=',', dtype='float')

x_data = import_data[1:, 2:]
y_data = []

for i in range(1, len(import_data)):
    temp = []
    temp.append(import_data[i][1])
    y_data.append(temp)

scaler = MinMaxScaler(feature_range=(0, 1))
x_data = scaler.fit_transform(x_data)
    
print(x_data)
print(y_data)

X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

H = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(H - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.001)
train = optimizer.minimize(cost)

print(np.shape(X))
print(np.shape(Y))
print(np.shape(W))
print(np.shape(b))

[[0.41044152 0.25957069 0.2       ]
 [0.50072194 0.24855662 0.24242424]
 [0.35139448 0.37024426 1.        ]
 [0.58507485 0.34626203 0.12121212]
 [1.         1.         0.93939394]
 [0.4106695  0.2938564  0.66666667]
 [0.1821187  0.14641007 0.39393939]
 [0.6238316  0.33382679 0.3030303 ]
 [0.20030967 0.10747594 0.30555556]
 [0.51639562 0.35255366 0.25      ]
 [0.41033703 0.39896373 1.        ]
 [0.21859564 0.08874907 0.55555556]
 [0.17209704 0.12294597 0.05555556]
 [0.23270195 0.         0.33333333]
 [0.61931948 0.44618801 0.86111111]
 [0.31159283 0.10340489 0.        ]
 [0.63185842 0.44048853 0.69444444]
 [0.30271107 0.19785344 0.        ]
 [0.41294931 0.23449297 0.        ]
 [0.25255529 0.12864545 0.58333333]
 [0.0575184  0.0324432  1.        ]
 [0.38111968 0.45332802 0.46153846]
 [0.59813991 0.67128623 0.64102564]
 [0.54846639 0.52472812 0.05128205]
 [0.48336032 0.40297216 0.33333333]
 [0.48914753 0.35787736 0.69230769]
 [0.41487838 0.13766441 0.25641026]
 [0.22582965 0.13616125 0.79

In [3]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(50001):
        _cost, _H, _W, _b, _ = sess.run([cost,H, W, b, train], feed_dict={X:x_data, Y:y_data})
        if(step % 10000 == 0):
            print(step," ", _cost," ", _W, " ",_b, " ")
    
    print("-----------------------------------")
    print(sess.run(H, feed_dict={X:x_data}))

0   3084.302   [[ 0.8434735 ]
 [ 0.70845574]
 [-1.1731633 ]]   [0.56463224]  
10000   217.95293   [[  8.41822  ]
 [ -1.4650718]
 [-16.571308 ]]   [57.753098]  
20000   201.12547   [[  3.807405]
 [ -8.501309]
 [-22.428274]]   [64.704735]  
30000   198.6975   [[  1.9123849]
 [-11.872541 ]
 [-23.735659 ]]   [67.15701]  
40000   198.26772   [[  1.3828996]
 [-13.5497055]
 [-24.094896 ]]   [68.06409]  
50000   198.16216   [[  1.4220235]
 [-14.494744 ]
 [-24.200241 ]]   [68.39146]  
-----------------------------------
[[60.372654]
 [59.634003]
 [39.32431 ]
 [61.271103]
 [32.585175]
 [48.58257 ]
 [56.994827]
 [57.10642 ]
 [59.723946]
 [57.965546]
 [38.991848]
 [53.97133 ]
 [65.50965 ]
 [60.655617]
 [41.965668]
 [67.335724]
 [46.099483]
 [65.95409 ]
 [65.579765]
 [52.769104]
 [43.80275 ]
 [51.193203]
 [43.998928]
 [60.32455 ]
 [55.17108 ]
 [47.145683]
 [60.780823]
 [47.50288 ]
 [54.719116]
 [42.377724]
 [47.498085]
 [62.38863 ]
 [61.327972]
 [51.673878]
 [55.709484]
 [63.466534]
 [60.43323 ]
 [